<?xml version="1.0" encoding="utf-8"?>
<Project>
  <Target Name="RenameMainMethod" BeforeTargets="CoreCompile" Condition="'$(AsApp)' != 'true'">
    <PropertyGroup>
      <ProgramCsPath>$(MSBuildProjectDirectory)\Program.cs</ProgramCsPath>
      <ProgramCsTempPath>$(IntermediateOutputPath)Program.temp.cs</ProgramCsTempPath>
    </PropertyGroup>

    <ReadLinesFromFile File="$(ProgramCsPath)">
      <Output TaskParameter="Lines" ItemName="OriginalProgramLines" />
    </ReadLinesFromFile>

    <ItemGroup>
      <ModifiedProgramLines Include="@(OriginalProgramLines->Replace('static async Task Main(string[] args)', 'static async Task Main_Not_As_App(string[] args)'))" />
    </ItemGroup>

    <WriteLinesToFile File="$(ProgramCsTempPath)" Lines="@(ModifiedProgramLines)" Overwrite="true" />

    <ItemGroup>
      <Compile Remove="Program.cs" />
      <Compile Include="$(ProgramCsTempPath)">
        <Link>Program.cs</Link>
      </Compile>
    </ItemGroup>
  </Target>
</Project>
