<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject Condition="'$(AsApp)' == 'true'">false</IsTestProject>
    <IsTestProject Condition="'$(AsApp)' != 'true'">true</IsTestProject>
    <OutputType Condition="'$(AsApp)' == 'true'">Exe</OutputType>
    <DefineConstants Condition="'$(AsApp)' == 'true'">$(DefineConstants);AS_APP</DefineConstants>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="coverlet.collector" Condition="'$(AsApp)' != 'true'" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Condition="'$(AsApp)' != 'true'" />
    <PackageReference Include="NUnit" Condition="'$(AsApp)' != 'true'" />
    <PackageReference Include="NUnit.Analyzers" Condition="'$(AsApp)' != 'true'" />
    <PackageReference Include="NUnit3TestAdapter" Condition="'$(AsApp)' != 'true'" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DevQAProdCom.NET.Global\DevQAProdCom.NET.Global.csproj" />
    <ProjectReference Include="..\DevQAProdCom.NET.DependencyInjection.Microsoft\DevQAProdCom.NET.DependencyInjection.Microsoft.csproj" />
    <ProjectReference Include="..\DevQAProdCom.NET.Logging.Providers.Serilog\DevQAProdCom.NET.Logging.Providers.Serilog.csproj" />
    <ProjectReference Include="..\DevQAProdCom.NET.Logging.Shared\DevQAProdCom.NET.Logging.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="NUnit.Framework" Condition="'$(AsApp)' != 'true'" />
  </ItemGroup>

  <ItemGroup Condition="'$(AsApp)' == 'true'">
    <Compile Remove="**\*Tests.cs" />
  </ItemGroup>

</Project>
