<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject Condition="'$(AsApp)' == 'true'">false</IsTestProject>
    <IsTestProject Condition="'$(AsApp)' != 'true'">true</IsTestProject>
    <OutputType Condition="'$(AsApp)' == 'true'">Exe</OutputType>
    <DefineConstants Condition="'$(AsApp)' == 'true'">$(DefineConstants);AS_APP</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Condition="'$(AsApp)' != 'true'" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit.Analyzers" />
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="coverlet.collector" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DevQAProdCom.NET.Global\DevQAProdCom.NET.Global.csproj" />
    <ProjectReference Include="..\DevQAProdCom.NET.DependencyInjection.Microsoft\DevQAProdCom.NET.DependencyInjection.Microsoft.csproj" />
    <ProjectReference Include="..\DevQAProdCom.NET.Logging.Providers.Serilog\DevQAProdCom.NET.Logging.Providers.Serilog.csproj" />
    <ProjectReference Include="..\DevQAProdCom.NET.Logging.Shared\DevQAProdCom.NET.Logging.Shared.csproj" />
  </ItemGroup>

  <!-- When building as app, replace Main_ForApp_With_This_Long_Name_Is_Changed_To_Just_Main_During_Build_AsApp with Main to create entry point -->
  <Target Name="RenameMainMethod" BeforeTargets="CoreCompile" Condition="'$(AsApp)' == 'true'">
    <PropertyGroup>
      <ProgramCsPath>$(MSBuildProjectDirectory)\Program.cs</ProgramCsPath>
      <ProgramCsTempPath>$(IntermediateOutputPath)Program.temp.cs</ProgramCsTempPath>
    </PropertyGroup>

    <!-- Read, replace, and write to intermediate output -->
    <ReadLinesFromFile File="$(ProgramCsPath)">
      <Output TaskParameter="Lines" ItemName="OriginalProgramLines" />
    </ReadLinesFromFile>

    <ItemGroup>
      <ModifiedProgramLines Include="@(OriginalProgramLines->Replace('Main_ForApp_With_This_Long_Name_Is_Changed_To_Just_Main_During_Build_AsApp', 'Main'))" />
    </ItemGroup>

    <WriteLinesToFile File="$(ProgramCsTempPath)" Lines="@(ModifiedProgramLines)" Overwrite="true" />

    <!-- Remove original and include modified version -->
    <ItemGroup>
      <Compile Remove="Program.cs" />
      <Compile Include="$(ProgramCsTempPath)">
        <Link>Program.cs</Link>
      </Compile>
    </ItemGroup>
  </Target>

</Project>
